#!/bin/sh
python3 ~/.scripts/weather.py

currentweather="/home/bigmac/Templates/currentweather"
getweather() { python3 "/home/bigmac/.scripts/weather.py" > "$currentweather" || exit 1 ;}

getweather

case $BUTTON in 
        1) getweather;;
        3) xdotool key "super+9" && google-chrome "https://www.google.com/search?q=weather" &;;
esac
